### ISSUE TITLE
Updates for traefik 2.0?

### ISSUE THREAD

**Issue by bubthegreat** [tiangolo/blog-posts#4]
This article/walkthrough is awesome, and I wish Traefik documentation was as good as your articles - but I can't seem to get things running properly in Traefik 2.0 - any chance you'll be rewriting/updating this to Traefik 2.0 syntax?

**Comment by tiangolo** [comment]
I'm glad you have liked these articles!

Yes, I plan on updating it on https://dockerswarm.rocks/, as soon as I get the time to do it :sweat_smile:
